sub init()
    m.poster = m.top.findNode("poster")
    m.skeleton = m.top.findNode("skeleton")

    m.poster.observeFieldScoped("loadStatus", "onPosterLoadStatusChanged")
end sub

sub onContentSet()
    content = m.top.itemContent
    if content = invalid then return
    
    if m.skeleton <> invalid then m.skeleton.visible = true
    m.poster.uri = content.thumbnailUrl
end sub

sub onPosterLoadStatusChanged(event as object)
    loadStatus = event.getData()
    if loadStatus = "ready"
        if m.skeleton <> invalid then m.skeleton.visible = false
    end if
end sub

sub onDestroy()
    m.poster = invalid
    m.skeleton = invalid
end sub
