sub init()
    m.top.backgroundURI = ""
    m.top.backgroundColor = "0x000000FF"
    m.loadingIndicator = m.top.findNode("loadingIndicator")
    
    ScreenStack.init()
    GridScreen.show()
    ContentTask.start()
end sub

function onKeyEvent(key as string, press as boolean) as boolean
    if not press then return false

    if key = "back"
        numberOfScreens = m.screenStack.count()
        if numberOfScreens > 1
            ScreenStack.close(invalid)
            return true
        end if
    end if

    return false
end function
